### ISSUE TITLE
`make full` hangs at the end

### ISSUE THREAD

**Issue by michaelklishin** [rabbitmq/rabbitmq-test#11]
At least when all test suites succeed, I've noticed that `make full` hangs at the end when stopping a node. I can terminate it and take running nodes down manually, so this seems like a test target(s) issue.

**Comment by dumbbell** [comment]
I believe this is the same hang seen by Jenkins. It should be fixed by rabbitmq/rabbitmq-server#465. Do you still see this problem?

**Comment by michaelklishin** [comment]
Nope.
