### ISSUE TITLE
Plugin dependencies support

### ISSUE THREAD

**Issue by hairyhum** [rabbitmq/rabbitmq-test#36]
Mqtt, Stomp plugins are dependencies of `rabbitmq_test` now (in `master` branch) and will be started during unit test run.
They are started with the same default port for both `rabbit` and `hare` nodes. Which cause node startup failure.

There are several test failing due to plugin dependencies.

**Comment by dumbbell** [comment]
Quick note about the migration to common_test: this won't be a problem because `rabbit_ct_broker_helpers` (a new module in rabbitmq-common), which takes care of starting nodes for the tests, computes a set of TCP port numbers for each required nodes.

**Comment by hairyhum** [comment]
But `master` tests cannot start, so we should have some workaround until common test migration is done.

**Comment by dumbbell** [comment]
Yes, I didn't mean to disagree with you. That was just to note we should not expect a regression with common_test.
